name: HSI_cls
channels:
  - soumith
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.14
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.8.13
  - readline=8.1.2
  - setuptools=63.4.1
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - pip:
    - charset-normalizer==2.1.1
    - cycler==0.11.0
    - einops==0.3.2
    - filelock==3.8.0
    - fvcore==0.1.5.post20221221
    - huggingface-hub==0.10.1
    - idna==3.4
    - imageio==2.13.1
    - iopath==0.1.10
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.3.3
    - networkx==2.8.7
    - numpy==1.19.4
    - packaging==21.3
    - pandas==1.4.4
    - pillow==9.2.0
    - portalocker==2.8.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.28.1
    - scikit-image==0.19.2
    - scikit-learn==0.24.1
    - scipy==1.7.1
    - seaborn==0.11.2
    - six==1.16.0
    - tabulate==0.9.0
    - termcolor==2.3.0
    - threadpoolctl==3.1.0
    - tifffile==2022.8.12
    - timm==0.6.11
    - torch==1.9.0
    - torchsummaryx==1.3.0
    - torchvision==0.10.0
    - tqdm==4.59.0
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - yacs==0.1.8